name: yoshi
description: Retrofit inspired HTTP Client generator for Dart
version: 0.0.1
author: "Jai Sachdeva"
homepage: null

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  analyzer: ">=0.40.0 <2.0.0"
  built_collection: ^4.3.2
  http: ^0.12.2